name: Sync Fork with Upstream

on:
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "m.kats@hotmail.com"
          git config --global user.name "mkatsilieris"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/BikS2013/AzWrap.git
          git fetch upstream

      - name: Rebase from upstream
        run: |
          git checkout main
          git rebase upstream/main

      - name: Push to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} main --force
